### ISSUE TITLE
Fix fragility

### ISSUE THREAD

**Issue by KOLANICH** [bokand/ScrollToTextFragment#12]
The proposed kind of URIs is fragile. It can be broken by minor changes in text. It would cause dead links.

The proposed solution:

1. require a mandatory fallback `id` of the immediate parent element.  Treat links without it as ordinary links. Search only inside of that element for performance optimization. Use parent element `id` as a fallback when the match is not found.

2. introduce fuzzy searches, for example some limited language-morphology based regex, fuzzy hash or even sentence embedding vector.

**Comment by dwhly** [comment]
Fuzzy anchoring is one benefit of the approach in the W3C note being discussed here: https://github.com/bokand/ScrollToTextFragment/issues/4

**Comment by bokand** [comment]
I'd hesitate to tie ids to it as 1) there may not be a nearby id available or it may be physically far away from the text 2) What happens if the id is invalid? What if the id changed but the text remains valid. It seems that it's adding as much fragility as it might take away.

Fuzzy searches I agree can be useful and they're being discussed in #4 as @dwhly mentions so I'm going to close this issue in favour of that one.
