### ISSUE TITLE
location.hash alternative

### ISSUE THREAD

**Issue by Maxim-Mazurok** [bokand/ScrollToTextFragment#16]
If we will decide to go with URL-based solution, we should consider adding an alternative to `location.hash` that will retrieve `targetText` from the URL.

**Comment by bokand** [comment]
This could be a nice little addition but I don't see it as adding a ton of value.

However, an API to let the author access the matched text would be very valuable since mapping the `targetText` selector to matched text is non-trivial. I could see use cases where an author might want to do something with matched text which is difficult without an API like this.

**Comment by bokand** [comment]
I think this is basically the same issue as #2 so I'm going to close it in favor of that.
