### ISSUE TITLE
Commas in the targetText, and other design issues

### ISSUE THREAD

**Issue by wumpus** [bokand/ScrollToTextFragment#6]
What if I want to link to targetText that contains a comma?

What does whitespace mean in targetText? Browsers frequently do not display whitespace the same as the source html, for example \n might be rendered as a space. Or two spaces in the html might be rendered as a single space.

Looks like the web annotation community has already thought about the whitespace issue, here's one example discussion: https://github.com/w3c/web-annotation/issues/221

**Comment by kevinmarks** [comment]
You can %-escape the comma, though using them unescaped is OK in a fragment. 
eg http://www.kevinmarks.com/poemfragmentions.html#Do%20not%20go%20gentle%20into%20that%20good%20night.%20Rage,%20rage%20against%20the%20dying%20of%20the%20light.

works fine.
The model we used in the fragmention js is to treat whitespace the way HTML does - using innnerText/textContent, then replacing whitespace with single spaces. 

`(element.innerText || element.textContent || '').replace(/\s+/g, ' ').indexOf(text)`

**Comment by wumpus** [comment]
Your documentation says that a comma is used to separate startPiece and endPiece. See: https://github.com/bokand/ScrollToTextFragment#extended-syntax

**Comment by bokand** [comment]
Commas in the content must be [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) by replacing instances with '%2C'. This is handled by the current experimental implementation, e.g.

`https://en.wikipedia.org/wiki/Dog#targetText=various%20behaviors%2C%20sensory%20capabilities`

Would match the text: "various behaviors, sensory capabilities"

**Comment by wumpus** [comment]
1. Your documentation doesn't say this, and it's not obvious

2. That's a terrible choice. Lots of url handling code will turn %2C into a comma pretty early in processing.

**Comment by bokand** [comment]
> 1. Your documentation doesn't say this, and it's not obvious

Thanks, I've updated the section on encoding to make that clearer.

> 2. That's a terrible choice. Lots of url handling code will turn %2C into a comma pretty early in processing.

Can you clarify what url handling code you're referring to and how this might affect the proposal?

**Comment by wumpus** [comment]
Most code that handles URLs uses libraries to do it. Many of these libraries helpfully unquote things for you. %2C is an unnecessary quote because it's not a delimiter. As a concrete example, the yarl python package is used for URL processing by aiohttp, which is used to write crawlers:

```
>>> from yarl import URL
>>> URL('http://example.com/?foo=%2C')
URL('http://example.com/?foo=,')
```

I'm not enough of an expert on the URI RFCs to say that depending on %2C being different from , is a bug or not. But I'm sure that in practice, it will cause indigestion to a lot of folks in the ecosystem.

**Comment by bokand** [comment]
We're only depending on the difference in the fragment navigation algorithm which is internal to the browser.

For everything else, I think existing code would already have to support either %2C or , being in the fragment (my guess is things like crawlers that use URLs in the way above would just drop fragments or treat them as opaque) since the fragment can already contain those characters.

Either the code wants to parse the text fragment, in which case it would need to know to unescape after separating, or it doesn't know/care about text fragments in which case it shouldn't matter that "start%2Cstring,end"  is turned into "start,string,end".

I'm happy to look at real-world cases as they come up and reevaluate but I don't see this as an issue right now.
